# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    # Runs a set of commands using the runners shell
    - name: Intall tools
      run: |
        sudo apt-get -y install rubygems ruby-dev zlib1g-dev
        sudo gem install bundler github-pages jekyll
        
    - name: Run publish.sh
      run: | 
        ./publish.sh
        git branch
        git log --oneline
