name: CI

on:
  pull_request:
    branches: [ master ]
    types: [closed] 

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Intall tools  
      run: |
        sudo apt-get -y install rubygems ruby-dev zlib1g-dev
        sudo gem install bundler github-pages jekyll
        
    - name: Run publish.sh
      run: | 
        sudo ./publish.sh
        git push origin asf-site:asf-site
