name: CI

on:
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Intall tools
      run: |
        sudo apt-get -y install rubygems ruby-dev zlib1g-dev

    - name: Run publish.sh
      run: |
        export GEM_HOME=$HOME/.gem
        export PATH=$PATH:$GEM_HOME/bin
        ./publish.sh
        git push origin asf-site:asf-site
